# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'BayTest'

target 'BayTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BayTest

  target 'BayTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BayTestUITests' do
    # Pods for testing
  end

end

target 'Data' do
  xcodeproj ‘Shares/Data/Data.xcodeproj’
  pod 'Moya/Combine', '~> 15.0'
end

target 'Core' do
  xcodeproj ‘Core/Core.xcodeproj’
  pod 'Moya/Combine', '~> 15.0'
end
